# Generated by Django 3.1.3 on 2021-12-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
