# Generated by Django 3.1.3 on 2021-12-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='donation',
        ),
    ]
